import os, argparse, requests, base64, modal
import sib_api_v3_sdk
from sib_api_v3_sdk.rest import ApiException
#from PIL import Image
#from io import BytesIO
from dotenv import load_dotenv
from db import update_content_image

load_dotenv()

#email setup
configuration = sib_api_v3_sdk.Configuration()
configuration.api_key['api-key'] = os.getenv("SIB_API_V3_KEY")
api_instance = sib_api_v3_sdk.TransactionalEmailsApi(sib_api_v3_sdk.ApiClient(configuration))

#function to send the image to the user
def send_email_with_attachment( to_address, prompt, image_bytes, filename):
    #Encode the image in Base64
    image_base64 = base64.b64encode(image_bytes).decode('utf-8')
    #create a SendSmtEmailAttachement object
    attachment=sib_api_v3_sdk.SendSmtpEmailAttachment(content=image_base64, name=filename)
    
    # High-end HTML Template
    html_content = f"""
    <html>
    <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f4f4f7; margin: 0; padding: 0;">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" style="padding: 20px;">
            <tr>
                <td align="center">
                    <table width="600" border="0" cellspacing="0" cellpadding="0" style="background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 10px rgba(0,0,0,0.1);">
                        <tr>
                            <td style="background-color: #5865F2; padding: 30px; text-align: center; color: white;">
                                <h1 style="margin: 0; font-size: 24px;">Your AI Masterpiece</h1>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 40px; text-align: center;">
                                <p style="font-size: 16px; color: #555;">Your creation for the prompt:</p>
                                <p style="font-size: 20px; font-weight: bold; color: #1a1a1a; font-style: italic; margin-bottom: 25px;">"{prompt}"</p>
                                
                                <div style="margin-bottom: 30px;">
                                     <img src="cid:preview_img" alt="Your AI Art" style="width: 100%; max-width: 500px; border-radius: 8px; border: 1px solid #eee; box-shadow: 0 4px 12px rgba(0,0,0,0.08);">
                                </div>

                                <p style="color: #666; font-size: 14px; line-height: 1.6;">
                                    We've attached the high-resolution PNG to this email. 
                                    You can also find it in your gallery on our website.
                                </p>
                            </td>
                        </tr>
                        <tr>
                            <td style="background-color: #f9f9f9; padding: 20px; text-align: center; font-size: 12px; color: #aaa;">
                                Generated by AI Generator • Powered by Modal GPU
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
    </html>
    """
    #create a sendsmtp Email object with attachment
    send_smtp_email = sib_api_v3_sdk.SendSmtpEmail(
        to=[{ "email":to_address, "name": to_address.split("@")[0] }],
        html_content=html_content,
        sender={"name": "AI Masterpiece", "email": "gptagent.unlock@gmail.com"},
        subject=f"🎨 Your AI Art : {prompt[:30]}...",
        attachment=[attachment]) #attach the image here

    try:
        #send the email
        api_instance.send_transac_email(send_smtp_email)
        print(f"✅ Beautiful email sent to {to_address}")
    except ApiException as e:
        print(f"Email Failed:{e}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    #parser.add_argument('--file_path', type=str, required=True)
    parser.add_argument('--email', type=str, required=True)
    parser.add_argument('--prompt', type=str, required=True)
    parser.add_argument('--file_id', type=str, required=True)
    args = parser.parse_args()

    #f = modal.Function.from_name("diffusion-service", "DiffusionModel.generate_and_save")
    DiffusionModel = modal.Cls.from_name("diffusion-service", "DiffusionModel")
    filename, image_bytes = DiffusionModel().generate_and_save.remote(args.email, args.prompt, args.file_id)

    os.makedirs("static/generated", exist_ok=True)
    static_path = f"static/generated/{filename}"
    with open(static_path, "wb") as f_out:
        f_out.write(image_bytes)

    browser_visible_url = f"/generated/{filename}"
    #DB_FILE = os.environ.get("DB_FILE", "sqlite3_database.db")
    
    update_content_image(args.file_id, browser_visible_url)
    print(f"SQLite database updated for file_id: {args.file_id}")

    send_email_with_attachment(args.email, args.prompt, image_bytes, filename)
    print("Done! Email sent successfully and Image saved to {static_path}")

